New log file opened at Fri Jul 28 22:01:22 EDT 2017 by 4102@Aruls-Air.wv.cc.cmu.edu
Taking next connection to: 51614
New client attempting to connect on port: 51615-51614
  Address = /128.237.160.61:51614
This client on port 51615 has uuid f4a9a132-3e7b-40d2-9a15-195630625089 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-f4a9a132-3e7b-40d2-9a15-195630625089
Taking next connection to: 51614
New client attempting to connect on port: 51617-51614
  Address = /128.237.160.61:51614
Handshake exception on socket: 51617
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 51614
New client attempting to connect on port: 51618-51614
  Address = /128.237.160.61:51614
This client on port 51618 has uuid dcea5887-f4b1-40d2-8dcd-9f3756c8f0ac configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-f4a9a132-3e7b-40d2-9a15-195630625089, play-fork-run-dcea5887-f4b1-40d2-8dcd-9f3756c8f0ac
Taking next connection to: 51614
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 51614
New client attempting to connect on port: 51755-51614
  Address = /128.237.160.61:51614
Handshake exception on socket: 51755
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 51614
New client attempting to connect on port: 51756-51614
  Address = /128.237.160.61:51614
This client on port 51756 has uuid c4ef7d91-62ea-482c-aa97-d2b5f3cf2a59 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-f4a9a132-3e7b-40d2-9a15-195630625089, play-fork-run-c4ef7d91-62ea-482c-aa97-d2b5f3cf2a59
Taking next connection to: 51614
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 51614
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 51614
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 51614
New client attempting to connect on port: 53286-51614
  Address = /128.237.160.61:51614
Handshake exception on socket: 53286
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 51614
New client attempting to connect on port: 53287-51614
  Address = /128.237.160.61:51614
This client on port 53287 has uuid 256496be-1bd5-4a16-9574-94c7255133c4 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-f4a9a132-3e7b-40d2-9a15-195630625089, play-fork-run-256496be-1bd5-4a16-9574-94c7255133c4
Taking next connection to: 51614
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 51614
